name: CI
on:
  push:
    branches: [ master ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm ci
      - run: make lint
      - run: make test-coverage
      - uses: paambaati/codeclimate-action@v2.6.0
        if: ${{ failure() || success() }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TOKEN }}
        with:
          coverageCommand: true
